name: cadnet
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.9
    - numpy
    - pytorch::pytorch 
    - pytorch::torchvision 
    - pytorch::torchaudio 
    - pytorch::cpuonly
    - tensorboard
    - pyg::pyg
    - pythonocc-core=7.5.1
    - occt=7.5.1
    - pip
